
Due to MODULEPATH changes, the following have been reloaded:
  1) GCCcore/.11.3.0     3) StdEnv/2023        5) zlib/.1.2.12
  2) Stages/2023         4) binutils/.2.38

Avalaible threads: 24
DEBUG
Namespace(gin='/p/project/hai_rnareplearn/RNARepLearn/config/Models/pretrain_RPI.gin', output='/p/project/hai_rnareplearn/RUNS/600k_pretraining/runsRPI/fold0', dataset_path='/p/project/hai_rnareplearn/under_300', dataset_type='GFILE', test_on_train=False, dataset_names=None, write_datasets=False, train_indices='/p/project/hai_rnareplearn/RUNS/600k_pretraining/indices/folds/fold0/train.indices', val_indices='/p/project/hai_rnareplearn/RUNS/600k_pretraining/indices/folds/fold0/val.indices', test_indices=None, eval_model=None, train_split=None, val_split=None, test_split=None, data_parallel=False, train_mode=None, model_state_dict=None, lr=None)
None
Traceback (most recent call last):
  File "/p/project/hai_rnareplearn/miniconda3/envs/RL/bin/rnareplearn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/p/project/hai_rnareplearn/miniconda3/envs/RL/lib/python3.11/site-packages/RNARepLearn/command_line.py", line 89, in main
    train_loader, val_loader, test_loader, batch_size = setup(basepath=args.dataset_path, dataset_names=args.dataset_names, dataset_type=args.dataset_type, train_val_test_splits=splits, indices=indices)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project/hai_rnareplearn/miniconda3/envs/RL/lib/python3.11/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/p/project/hai_rnareplearn/miniconda3/envs/RL/lib/python3.11/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/p/project/hai_rnareplearn/miniconda3/envs/RL/lib/python3.11/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project/hai_rnareplearn/miniconda3/envs/RL/lib/python3.11/site-packages/RNARepLearn/command_line.py", line 110, in setup
    raise Exception("No valid application mode defined")
Exception: No valid application mode defined
  In call to configurable 'setup' (<function setup at 0x14f1985a3ce0>)
